### ISSUE TITLE
Can't get .ics timetable

### ISSUE THREAD

**Issue by elijahzyx** [bddvlpr/untis-ics-sync#30]
When I go to http://localhost:3000/lessons/96 I can view all the data, but when I try to get the ics from http://localhost:3000/lessons/96/ics I get this error:
`{"statusCode":500,"message":"Internal server error"}`

**Comment by bddvlpr** [comment]
Any output in the logs? Which version are you running?

**Comment by HotUrsula** [comment]
```server-1  | [Nest] 1  - 04/30/2024, 2:25:15 PM   DEBUG [UntisService] Cache for TIMETABLE.96 exists.
server-1  | [Nest] 1  - 04/30/2024, 2:25:15 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
server-1  | [Nest] 1  - 04/30/2024, 2:25:15 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'map')
server-1  | Error: Cannot read properties of undefined (reading 'map')
server-1  |     at Queue.onFailed (/app/node_modules/bull/lib/job.js:516:18)
server-1  |     at Queue.emit (node:events:518:28)
server-1  |     at module.exports.emitSafe (/app/node_modules/bull/lib/utils.js:50:20)
server-1  |     at EventEmitter.messageHandler (/app/node_modules/bull/lib/queue.js:476:15)
server-1  |     at EventEmitter.emit (node:events:518:28)
server-1  |     at DataHandler.handleSubscriberReply (/app/node_modules/ioredis/built/DataHandler.js:80:32)
server-1  |     at DataHandler.returnReply (/app/node_modules/ioredis/built/DataHandler.js:47:18)
server-1  |     at JavascriptRedisParser.returnReply (/app/node_modules/ioredis/built/DataHandler.js:21:22)
server-1  |     at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:544:14)
server-1  |     at Socket.<anonymous> (/app/node_modules/ioredis/built/DataHandler.js:25:20)```

newest version of everything

**Comment by bddvlpr** [comment]
Will fix it in about an hour. :)

**Comment by HotUrsula** [comment]
Alright, thank you very much :)

**Comment by bddvlpr** [comment]
Could you provide the output of the non /ics path so I can figure out which property is undef? You can also e-mail or send it through a private channel if required. Seems like the typings aren't correct (again)...

**Comment by elijahzyx** [comment]
I have e-mailed it to you!

**Comment by elijahzyx** [comment]
Sadly, I'm still getting the same error :/

`{"statusCode":500,"message":"Internal server error"}`

**Comment by bddvlpr** [comment]
Are you sure you pulled the latest image? I'll look into replicating your issue tomorrow.

**Comment by elijahzyx** [comment]
Yeah pretty sure

**Comment by bddvlpr** [comment]
Tried running it locally with your data, seems to pass. Are you sure you pulled the new image?

**Comment by elijahzyx** [comment]
Reinstalled on another pc, worked now. Thanks!
